/**
 * 50 vins les plus recherchés en France, Europe et international
 * Données basées sur Wine-Searcher, Vivino et tendances de recherche
 */

export interface WineData {
  slug: string;
  name: string;
  region: string;
  country: string;
  type: string;
  description: string;
  keywords: string[];
}

export const WINES: WineData[] = [
  // France — Bordeaux & grands crus
  { slug: 'chateau-margaux', name: 'Château Margaux', region: 'Margaux, Bordeaux', country: 'France', type: 'Rouge', description: 'Château Margaux est l\'un des cinq premiers crus classés du Médoc. Ce grand cru bordelais produit des vins d\'exception à base de Cabernet Sauvignon et Merlot, réputés pour leur élégance, leur finesse tannique et leur potentiel de garde exceptionnel.', keywords: ['château margaux', 'bordeaux', 'premier cru', 'médoc'] },
  { slug: 'chateau-lafite-rothschild', name: 'Château Lafite Rothschild', region: 'Pauillac, Bordeaux', country: 'France', type: 'Rouge', description: 'Château Lafite Rothschild, premier cru classé de Pauillac, est l\'un des vins les plus prestigieux au monde. Son Cabernet Sauvignon dominant offre puissance, complexité et une garde légendaire.', keywords: ['lafite', 'pauillac', 'bordeaux', 'premier cru'] },
  { slug: 'chateau-latour', name: 'Château Latour', region: 'Pauillac, Bordeaux', country: 'France', type: 'Rouge', description: 'Château Latour, premier cru classé de Pauillac, produit des vins puissants et structurés. Réputé pour sa constance et son potentiel de garde de plusieurs décennies.', keywords: ['latour', 'pauillac', 'bordeaux'] },
  { slug: 'chateau-mouton-rothschild', name: 'Château Mouton Rothschild', region: 'Pauillac, Bordeaux', country: 'France', type: 'Rouge', description: 'Château Mouton Rothschild, premier cru classé depuis 1973, allie puissance et finesse. Ses étiquettes artistiques et ses vins d\'exception en font une référence mondiale.', keywords: ['mouton', 'rothschild', 'pauillac', 'bordeaux'] },
  { slug: 'chateau-haut-brion', name: 'Château Haut-Brion', region: 'Pessac-Léognan, Bordeaux', country: 'France', type: 'Rouge', description: 'Château Haut-Brion est le seul premier cru classé de Graves. Ses vins rouges et blancs se distinguent par leur minéralité et leur complexité aromatique unique.', keywords: ['haut-brion', 'graves', 'pessac-léognan'] },
  { slug: 'petrus', name: 'Pétrus', region: 'Pomerol, Bordeaux', country: 'France', type: 'Rouge', description: 'Pétrus, domaine emblématique de Pomerol, produit l\'un des vins les plus recherchés au monde. 100 % Merlot sur sol argileux, il offre une richesse et une rondeur incomparables.', keywords: ['pétrus', 'pomerol', 'merlot', 'bordeaux'] },
  { slug: 'chateau-dyquem', name: 'Château d\'Yquem', region: 'Sauternes, Bordeaux', country: 'France', type: 'Blanc liquoreux', description: 'Château d\'Yquem est le plus célèbre des Sauternes. Ce vin liquoreux noble à base de Sémillon et Sauvignon offre une richesse, une complexité et une longueur exceptionnelles.', keywords: ['yquem', 'sauternes', 'liquoreux', 'bordeaux'] },
  { slug: 'domaine-romanee-conti', name: 'Domaine de la Romanée-Conti', region: 'Bourgogne', country: 'France', type: 'Rouge', description: 'Le Domaine de la Romanée-Conti (DRC) produit les Pinot Noir les plus convoités au monde. Romanée-Conti, La Tâche et les autres grands crus de Vosne-Romanée sont des références absolues.', keywords: ['romanée-conti', 'DRC', 'bourgogne', 'pinot noir'] },
  // France — Appellations génériques
  { slug: 'sancerre', name: 'Sancerre', region: 'Loire', country: 'France', type: 'Blanc', description: 'Le Sancerre est un vin blanc de la Loire à base de Sauvignon Blanc. Sec, minéral et aromatique, il est l\'accord parfait avec les fruits de mer et les fromages de chèvre.', keywords: ['sancerre', 'sauvignon', 'loire', 'blanc'] },
  { slug: 'chablis', name: 'Chablis', region: 'Bourgogne', country: 'France', type: 'Blanc', description: 'Le Chablis est un Chardonnay de Bourgogne septentrionale. Sec, minéral et souvent sans bois, il exprime le terroir kimméridgien de façon unique.', keywords: ['chablis', 'chardonnay', 'bourgogne', 'blanc'] },
  { slug: 'cotes-du-rhone', name: 'Côtes du Rhône', region: 'Vallée du Rhône', country: 'France', type: 'Rouge', description: 'Les Côtes du Rhône sont des vins rouges généreux à base de Grenache, Syrah et Mourvèdre. Fruités, épicés et accessibles, ils accompagnent parfaitement la cuisine du Sud.', keywords: ['côtes du rhône', 'rhône', 'grenache', 'syrah'] },
  { slug: 'chateauneuf-du-pape', name: 'Châteauneuf-du-Pape', region: 'Vallée du Rhône', country: 'France', type: 'Rouge', description: 'Châteauneuf-du-Pape est l\'appellation phare du Rhône méridional. Vins puissants, épicés et généreux, élaborés à partir de treize cépages autorisés.', keywords: ['châteauneuf-du-pape', 'rhône', 'cdp'] },
  { slug: 'champagne', name: 'Champagne', region: 'Champagne', country: 'France', type: 'Effervescent', description: 'Le Champagne est le vin effervescent d\'exception par excellence. Chardonnay, Pinot Noir et Meunier produisent des bulles fines, complexes et festives.', keywords: ['champagne', 'effervescent', 'bulles', 'champagne'] },
  { slug: 'dom-perignon', name: 'Dom Pérignon', region: 'Champagne', country: 'France', type: 'Effervescent', description: 'Dom Pérignon est le prestige cuvée de Moët & Chandon. Chaque millésime est une sélection rigoureuse pour un Champagne d\'exception, puissant et raffiné.', keywords: ['dom pérignon', 'champagne', 'moët', 'prestige'] },
  { slug: 'veuve-clicquot', name: 'Veuve Clicquot', region: 'Champagne', country: 'France', type: 'Effervescent', description: 'Veuve Clicquot est une maison de Champagne réputée pour ses cuvées Yellow Label et La Grande Dame. Style puissant, riche et généreux.', keywords: ['veuve clicquot', 'champagne', 'yellow label'] },
  { slug: 'saint-emilion', name: 'Saint-Émilion', region: 'Bordeaux', country: 'France', type: 'Rouge', description: 'Saint-Émilion produit des vins rouges élégants à base de Merlot et Cabernet Franc. Terroirs variés, de la plaine aux côtes, pour des vins d\'une grande diversité.', keywords: ['saint-émilion', 'bordeaux', 'merlot'] },
  { slug: 'pomerol', name: 'Pomerol', region: 'Bordeaux', country: 'France', type: 'Rouge', description: 'Pomerol est l\'appellation de Pétrus et de nombreux domaines d\'exception. Vins dominés par le Merlot, ronds, riches et généreux.', keywords: ['pomerol', 'bordeaux', 'merlot'] },
  { slug: 'pouilly-fume', name: 'Pouilly-Fumé', region: 'Loire', country: 'France', type: 'Blanc', description: 'Le Pouilly-Fumé est un Sauvignon Blanc de la Loire, réputé pour ses notes fumées et minérales. Cousin du Sancerre, il offre un style unique.', keywords: ['pouilly-fumé', 'sauvignon', 'loire'] },
  { slug: 'cote-roties', name: 'Côte-Rôtie', region: 'Vallée du Rhône', country: 'France', type: 'Rouge', description: 'La Côte-Rôtie produit des vins rouges élégants à base de Syrah et Viognier. Terroirs en terrasses, vins puissants et aromatiques.', keywords: ['côte-rôtie', 'syrah', 'rhône'] },
  { slug: 'hermitage', name: 'Hermitage', region: 'Vallée du Rhône', country: 'France', type: 'Rouge', description: 'L\'Hermitage est un grand cru septentrional du Rhône. Syrah pure pour des vins puissants, épicés et de garde exceptionnelle.', keywords: ['hermitage', 'syrah', 'rhône'] },
  { slug: 'condrieu', name: 'Condrieu', region: 'Vallée du Rhône', country: 'France', type: 'Blanc', description: 'Le Condrieu est un Viognier d\'exception, rare et précieux. Vin blanc aromatique, floral et riche, parfait avec la cuisine raffinée.', keywords: ['condrieu', 'viognier', 'rhône'] },
  { slug: 'gigondas', name: 'Gigondas', region: 'Vallée du Rhône', country: 'France', type: 'Rouge', description: 'Le Gigondas est un vin rouge du Rhône méridional, proche du Châteauneuf. Structure, puissance et notes de fruits mûrs et d\'épices.', keywords: ['gigondas', 'rhône', 'grenache'] },
  { slug: 'bandol', name: 'Bandol', region: 'Provence', country: 'France', type: 'Rouge', description: 'Le Bandol est l\'appellation de Provence réputée pour ses vins rouges à base de Mourvèdre. Puissants, tanniques et de garde.', keywords: ['bandol', 'provence', 'mourvèdre'] },
  { slug: 'chateauneuf-du-pape-blanc', name: 'Châteauneuf-du-Pape blanc', region: 'Vallée du Rhône', country: 'France', type: 'Blanc', description: 'Le Châteauneuf-du-Pape blanc, rare et précieux, associe Roussanne, Grenache blanc et Clairette. Vin blanc riche, plein et aromatique.', keywords: ['châteauneuf blanc', 'rhône', 'blanc'] },
  { slug: 'chablis-grand-cru', name: 'Chablis Grand Cru', region: 'Bourgogne', country: 'France', type: 'Blanc', description: 'Les Chablis Grand Cru (Les Clos, Vaudésir, etc.) sont les Chardonnay les plus purs de Chablis. Minéralité, tension et longueur exceptionnelles.', keywords: ['chablis grand cru', 'chardonnay', 'bourgogne'] },
  { slug: 'meursault', name: 'Meursault', region: 'Bourgogne', country: 'France', type: 'Blanc', description: 'Le Meursault est un Chardonnay de la Côte de Beaune, réputé pour sa rondeur, ses notes de beurre et de noisette. Un grand blanc de Bourgogne.', keywords: ['meursault', 'chardonnay', 'bourgogne'] },
  { slug: 'gevrey-chambertin', name: 'Gevrey-Chambertin', region: 'Bourgogne', country: 'France', type: 'Rouge', description: 'Gevrey-Chambertin est le village des grands crus Chambertin et Chambertin-Clos de Bèze. Pinot Noir puissant, structuré et de garde.', keywords: ['gevrey-chambertin', 'pinot noir', 'bourgogne'] },
  { slug: 'alsace-riesling', name: 'Riesling d\'Alsace', region: 'Alsace', country: 'France', type: 'Blanc', description: 'Le Riesling d\'Alsace est sec, aromatique et minéral. Notes florales, d\'agrumes et de pierre à fusil. Accord parfait avec la choucroute.', keywords: ['riesling alsace', 'alsace', 'blanc'] },
  { slug: 'chianti', name: 'Chianti', region: 'Toscane', country: 'Italie', type: 'Rouge', description: 'Le Chianti est le vin emblématique de Toscane. Sangiovese dominant, il offre fraîcheur, acidité et notes de cerise et d\'épices.', keywords: ['chianti', 'toscane', 'sangiovese'] },
  { slug: 'barolo', name: 'Barolo', region: 'Piémont', country: 'Italie', type: 'Rouge', description: 'Le Barolo, « roi des vins », est un Nebbiolo du Piémont. Puissant, tannique, aux notes de rose et de truffe. Garde légendaire.', keywords: ['barolo', 'piémont', 'nebbiolo'] },
  { slug: 'barbaresco', name: 'Barbaresco', region: 'Piémont', country: 'Italie', type: 'Rouge', description: 'Le Barbaresco est le cousin du Barolo, plus élégant et moins tannique. Nebbiolo pur, notes de violette et de fruits rouges.', keywords: ['barbaresco', 'piémont', 'nebbiolo'] },
  { slug: 'amarone', name: 'Amarone della Valpolicella', region: 'Vénétie', country: 'Italie', type: 'Rouge', description: 'L\'Amarone est un vin rare à base de raisins passerillés. Puissant, riche en alcool, aux notes de cerise confite, pruneau et épices.', keywords: ['amarone', 'valpolicella', 'italie'] },
  { slug: 'brunello-di-montalcino', name: 'Brunello di Montalcino', region: 'Toscane', country: 'Italie', type: 'Rouge', description: 'Le Brunello di Montalcino est un Sangiovese pur de Toscane. Vin puissant, tannique, aux notes de fruits mûrs et d\'épices.', keywords: ['brunello', 'montalcino', 'toscane'] },
  { slug: 'prosecco', name: 'Prosecco', region: 'Vénétie', country: 'Italie', type: 'Effervescent', description: 'Le Prosecco est le vin effervescent italien par excellence. Glera, bulles fines, notes de poire et de fleurs blanches. Idéal à l\'apéritif.', keywords: ['prosecco', 'italie', 'effervescent', 'apéritif'] },
  { slug: 'sassicaia', name: 'Sassicaia', region: 'Bolgheri, Toscane', country: 'Italie', type: 'Rouge', description: 'Le Sassicaia est le premier Super Tuscan de Tenuta San Guido. Cabernet Sauvignon et Franc, style bordelais en Toscane.', keywords: ['sassicaia', 'super tuscan', 'bolgheri'] },
  { slug: 'chianti-classico', name: 'Chianti Classico', region: 'Toscane', country: 'Italie', type: 'Rouge', description: 'Le Chianti Classico, avec son symbole du Gallo Nero, est le Sangiovese pur des collines historiques. Structure, fraîcheur et typicité.', keywords: ['chianti classico', 'gallo nero', 'toscane'] },
  { slug: 'rioja', name: 'Rioja', region: 'Rioja', country: 'Espagne', type: 'Rouge', description: 'La Rioja est l\'appellation espagnole la plus réputée. Tempranillo dominant, vins élevés en fût, aux notes de vanille et de fruits rouges.', keywords: ['rioja', 'espagne', 'tempranillo'] },
  { slug: 'ribera-del-duero', name: 'Ribera del Duero', region: 'Castille-et-León', country: 'Espagne', type: 'Rouge', description: 'La Ribera del Duero produit des vins puissants à base de Tinto Fino (Tempranillo). Structure, tannins et potentiel de garde.', keywords: ['ribera del duero', 'espagne', 'tempranillo'] },
  { slug: 'priorat', name: 'Priorat', region: 'Catalogne', country: 'Espagne', type: 'Rouge', description: 'Le Priorat est une appellation catalane de vins rouges puissants. Grenache et Cariñena sur schistes, pour des vins concentrés et minéraux.', keywords: ['priorat', 'catalogne', 'espagne'] },
  { slug: 'cava', name: 'Cava', region: 'Catalogne', country: 'Espagne', type: 'Effervescent', description: 'Le Cava est le vin effervescent espagnol, méthode traditionnelle. Macabeu, Parellada et Xarel·lo pour des bulles fines et accessibles.', keywords: ['cava', 'espagne', 'effervescent'] },
  { slug: 'riesling-mosel', name: 'Riesling Mosel', region: 'Moselle', country: 'Allemagne', type: 'Blanc', description: 'Le Riesling de la Moselle est léger, aromatique et souvent légèrement sucré. Notes de pêche, d\'abricot et minéralité.', keywords: ['riesling mosel', 'allemagne', 'moselle'] },
  { slug: 'porto', name: 'Porto', region: 'Douro', country: 'Portugal', type: 'Muté', description: 'Le Porto est un vin muté fortifié du Douro. Ruby, Tawny ou Vintage, il offre richesse, douceur et notes de fruits confits.', keywords: ['porto', 'port', 'portugal'] },
  { slug: 'champagne-rose', name: 'Champagne rosé', region: 'Champagne', country: 'France', type: 'Effervescent', description: 'Le Champagne rosé associe la finesse des bulles à la fraîcheur des fruits rouges. Assemblage ou saignée, pour des moments festifs.', keywords: ['champagne rosé', 'rosé', 'champagne'] },
  { slug: 'provence-rose', name: 'Rosé de Provence', region: 'Provence', country: 'France', type: 'Rosé', description: 'Le rosé de Provence est léger, pâle et désaltérant. Cinsault, Grenache et Mourvèdre pour des notes de pêche et de fraise.', keywords: ['rosé provence', 'provence', 'rosé'] },
  { slug: 'malbec-argentine', name: 'Malbec argentin', region: 'Mendoza', country: 'Argentine', type: 'Rouge', description: 'Le Malbec argentin de Mendoza est devenu une référence mondiale. Fruits rouges, épices douces et tanins soyeux. Un vin généreux et accessible.', keywords: ['malbec', 'argentine', 'mendoza'] },
  { slug: 'napa-cabernet', name: 'Cabernet Sauvignon Napa', region: 'Napa Valley', country: 'États-Unis', type: 'Rouge', description: 'Le Cabernet Sauvignon de Napa Valley est puissant, riche en alcool et aux notes de cassis et de vanille. Référence du Nouveau Monde.', keywords: ['napa', 'cabernet', 'californie'] },
  { slug: 'sauvignon-marlborough', name: 'Sauvignon Blanc Marlborough', region: 'Marlborough', country: 'Nouvelle-Zélande', type: 'Blanc', description: 'Le Sauvignon Blanc de Marlborough est explosif : notes de fruits de la passion, de pamplemousse et d\'herbe coupée. Fraîcheur et typicité.', keywords: ['sauvignon marlborough', 'nouvelle-zélande', 'blanc'] },
  { slug: 'chablis-premier-cru', name: 'Chablis Premier Cru', region: 'Bourgogne', country: 'France', type: 'Blanc', description: 'Les Chablis Premier Cru (Montée de Tonnerre, Fourchaume, etc.) offrent un équilibre entre minéralité et rondeur. Chardonnay pur.', keywords: ['chablis premier cru', 'chardonnay', 'bourgogne'] },
  { slug: 'bordeaux', name: 'Bordeaux', region: 'Bordeaux', country: 'France', type: 'Rouge', description: 'Le Bordeaux est l\'appellation générique des vins de la région. Merlot et Cabernet Sauvignon pour des vins rouges structurés et de garde.', keywords: ['bordeaux', 'rouge', 'médoc'] },
  { slug: 'bourgogne', name: 'Bourgogne', region: 'Bourgogne', country: 'France', type: 'Rouge', description: 'La Bourgogne produit des Pinot Noir d\'exception. Chambolle-Musigny, Nuits-Saint-Georges, Gevrey : des terroirs uniques au monde.', keywords: ['bourgogne', 'pinot noir', 'bourgogne'] },
  { slug: 'chinon', name: 'Chinon', region: 'Loire', country: 'France', type: 'Rouge', description: 'Le Chinon est un Cabernet Franc de la Loire. Vin rouge léger, fruité, aux notes de framboise et de poivron vert. À servir frais.', keywords: ['chinon', 'cabernet franc', 'loire'] },
  { slug: 'cote-de-beaune', name: 'Côte de Beaune', region: 'Bourgogne', country: 'France', type: 'Blanc', description: 'La Côte de Beaune est le berceau des grands Chardonnay : Meursault, Puligny-Montrachet, Chassagne-Montrachet. Richesses et finesse.', keywords: ['côte de beaune', 'chardonnay', 'bourgogne'] },
  { slug: 'cotes-de-provence', name: 'Côtes de Provence', region: 'Provence', country: 'France', type: 'Rosé', description: 'Les Côtes de Provence produisent les rosés les plus célèbres de France. Pâle, frais et désaltérant, idéal à l\'apéritif.', keywords: ['côtes de provence', 'rosé', 'provence'] },
  { slug: 'champagne-brut', name: 'Champagne Brut', region: 'Champagne', country: 'France', type: 'Effervescent', description: 'Le Champagne Brut est le style le plus courant : sec, équilibré, aux bulles fines. Idéal à l\'apéritif ou pour accompagner les plats.', keywords: ['champagne brut', 'champagne', 'sec'] },
];

export const WINES_BY_SLUG: Record<string, WineData> = Object.fromEntries(
  WINES.map((w) => [w.slug, w])
);

export function getWineBySlug(slug: string): WineData | undefined {
  return WINES_BY_SLUG[slug];
}
